### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by ilyail3newvem** [fanout/zurl#3] opened 2015-06-09 15:09 UTC
I love the idea of this project, but I ran into issues sending custom headers. Which is required for my use case to use against AWS API.

Whenever I send a header which isn't "Content-Length" in Json format, all I get is errors, from zurl itself.

Here's the log message
```
[DEBUG] 2015-06-09 10:57:38.337 recv-init: { "body": "Action=DescribeCacheEngineVersions&Version=2015-02-02", "method": "POST", "uri": "http://elasticache.us-west-1.amazonaws.com/", "from": "cw2miner", "headers": [ [ <unknown>, <unknown> ] ], "id": "80b4902c-db42-4637-ab40-fed64271d625" }
[WARN] 2015-06-09 10:57:38.337 failed to parse zurl request
[INFO] 2015-06-09 10:57:38.337 OUT ERR id=80b4902c-db42-4637-ab40-fed64271d625 condition=bad-request
[DEBUG] 2015-06-09 10:57:38.338 send: { "condition": "bad-request", "seq": 0, "from": "{758d5129-3c5b-4901-8549-44e5526b222c}", "type": "error", "id": "80b4902c-db42-4637-ab40-fed64271d625" }
```

I would've hacked it on my own, but unfortunately I don't see an easy way to allow custom headers.
Thanks

BTW, the headers look roughly like(Scrambled a bit for confidentiality, but exact values aren't necessary to replicate)
```
x-amz-date: 20150609T151035Z
Authorization: AWS4-HMAC-SHA256 Credential=AKIBIUAXWJG2ZX736A3A/23170412/sa-east-1/elasticache/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=184663e3d0cac180bc28c8b4261701a9ed9083f069e3847094c375cb7d0fab84
```

**Comment by jkarneges** [comment] 2015-06-12 00:27
Hmm, custom headers are definitely supported. Did the log output literally say "<unknown>" or did you censor it?

For example, I just tried adding this line to tools/get.py and it works:

  req['headers'] = [['Foo', 'Bar']]

**Comment by jkarneges** [comment] 2015-06-12 07:44
Found the issue. It was a problem when using JSON as the format (I was testing with TNetStrings). I believe I've fixed it.

**Comment by jkarneges** [comment] 2015-06-19 00:31
Closing the issue, since I believe the problem is fixed. Let me know if this is not the case.

**Closed by jkarneges** 2015-06-19 00:31 UTC
